[package]
name = "rust-sample-function"
version = "0.1.0"
authors = ["hisayuki"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lambda_runtime = ""
lambda_http = ""
log = ""
serde_json = ""
serde_derive = ""
